### ISSUE TITLE
Enhancement: run a test in a new browser instance, rather than the currently running one

### ISSUE THREAD

**Issue by leemke** [googlearchive/chromedeveditor#3370]
I would like to see an option/setting that would direct the "run" command to open a new instance
instead of opening in the current instance.  I can understand that sometimes some persons like
to pre-open the browser.  I, on the other hand, like a new clean instance when I relaunch a test.html
dataset. I think both options should be available.

Another reason I want a new instance, is that when I am done with a test, I have a tendency to close
the browser.  When this happens, it also closes all of the other tabs that are open. Then I have to spend time reopening the other tabs to reestablish where I was.

**Comment by ghost** [comment]
ok I have moved on to a new tool
