### ISSUE TITLE
The search box is messed up.

### ISSUE THREAD

**Issue by jasoncheng1024** [googlearchive/chromedeveditor#4050]
The search box is messed up and doesn't look right. It extends into the tabs part. It'd be nice if you could fix that.
![fdsaffffff](https://cloud.githubusercontent.com/assets/15603171/13021869/548ce606-d192-11e5-9013-4be7893fc151.png)

**Comment by murthag11** [comment]
Same here, I opened the Issue #4051 but then I saw this one. I included some further Screenshots though.

**Comment by b14ckcr0w** [comment]
It's a little more broken in my Chromebook Edition
Version 0.22.3529

http://i.imgur.com/DudN2Jo.png

**Comment by jasoncheng1024** [comment]
Yeah, but I uninstalled/installed Chrome Dev Editor and it became less messed up.

**Comment by ensan100** [comment]
#
بتاريخ ١٥‏/٠٢‏/٢٠١٦ ٩:٠٥ م، كتب "jasoncheng1024" <notifications@github.com>:

**Comment by jasoncheng1024** [comment]
I found out if you just resize the menu, everything's back to normal. But then again, they should make the search box automatically get resized to fit the menu's width.

**Comment by jasoncheng1024** [comment]
should I close the issue?

**Comment by murthag11** [comment]
@jasoncheng1024 I wouldn't, just having a workaround solution is nice but for users that freshly install it it's still an issue, and they don't know what we do now. I'd wait until the root problem is solved.
